### PR TITLE
Remove always_allow_html

### PR DESCRIPTION
**Pull request by maurolepore**

### CODE REVIEW

**Comment by cjyetman** [comment]
out of curiosity, was this causing a specific problem?

**Comment by MonikaFu** [comment]
> out of curiosity, was this causing a specific problem?

@cjyetman - from my understanding - not. It is more from the cleaning perspective -  if not necessary it should be removed.

**Review by MonikaFu — APPROVED** [review]
LGTM

**Review by MonikaFu — APPROVED** [review]
LGTM

**Comment by maurolepore** [comment]
> out of curiosity, was this causing a specific problem?
No, not at all.

**Comment by cjyetman** [comment]
> > out of curiosity, was this causing a specific problem?
> 
> No, not at all.

cool... then my repo is safe 😉

**Comment by maurolepore** [comment]
By now you surely know more than me but I suspect that option is a must for interactive output.

**Pull request merged**
