### PR TITLE
Add relevant sectors chart

### PR DESCRIPTION
**Pull request by MonikaFu**
Related to #10 

In this PR I add a meta-report chart displaying PACTA sectors coverage to the package. 

image

In particular I:
* Add a data processing function for '_overview_portfolio.rda' dataset
* Add a plotting function displaying the information in a form of 'small multiples' for Equity and Bond separately.

### CODE REVIEW

**Comment by cjyetman** [comment]
FYI, tests on R v3.5 and R v3.4 fail because
> Error: Package required but not available: ‘ggpubr’
> ERROR: dependencies ‘cowplot’, ‘rstatix’ are not available for package ‘ggpubr’

you may have a dependency on R v3.6+ now

**Comment by MonikaFu** [comment]
Thanks for pointing it out @cjyetman . Any advice on how to proceed? Maybe @maurolepore ?

**Comment by cjyetman** [comment]
probably need to specify that in DESCRIPTION and probably then remove those tests from the GitHub action that's running CI

**Review by jdhoffa — CHANGES_REQUESTED** [review]
Could you add an example into @examples of `prepare_for_pacta_sectors_chart` and `plot_metareport_pacta_sectors`? It will make it easier to test the output, and also is helpful to have that documentation for future users. 

(Something like `get_example_data() %>% prepare_for_pacta_sectors_chart() %>% plot_metareport_pacta_sectors()`)

**Comment by cjyetman** [comment]
I would wait for @maurolepore to comment though.... 
[ggpubr](https://CRAN.R-project.org/package=ggpubr) officially depends on v3.1.0
[cowplot](https://CRAN.R-project.org/package=cowplot) officially depends on v3.5.0
[rstatix](https://CRAN.R-project.org/package= rstatix) officially depends on v3.3.0

so honestly, I don't know why their installs are failing on the v3.5 test, though the v3.4 may obviously be because it can't install cowplot

**Comment by MonikaFu** [comment]
> Could you add an example into @examples of `prepare_for_pacta_sectors_chart` and `plot_metareport_pacta_sectors`? It will make it easier to test the output, and also is helpful to have that documentation for future users.
> 
> (Something like `get_example_data() %>% prepare_for_pacta_sectors_chart() %>% plot_metareport_pacta_sectors()`)

@jdhoffa at the moment I can't because I do not have 'toy' meta report data. I could work on creating it but I thought that it might not be of highest priority at the moment.

**Comment by cjyetman** [comment]
I think the dependency path is....
ggpubr->rstatix->car->lme4-> nloptr->A system installation of NLopt

which results in...
> ERROR: configuration failed for package ‘nloptr’
because it fails to make the underlying system dependencies (nlopt and its dependencies)

Welcome to dependency hell! 🔥

**Comment by maurolepore** [comment]
Thanks CJ for noticing the dependency issues. I just pushed a commit that removes the broken checks on CI. I expect to re-enter the green zone. Eventually we can work to support older versions of R, but at this stage the priority seems to be to get software to beta users quickly so we can learn what we really want to build. 

Feel free to revert if this solution is not what you want.

**Comment by MonikaFu** [comment]
> Thanks CJ for noticing the dependency issues. I just pushed a commit that removes the broken checks on CI. I expect to re-enter the green zone. Eventually we can work to support older versions of R, but at this stage the priority seems to be to get software to beta users quickly so we can learn what we really want to build.
> 
> Feel free to revert if this solution is not what you want.

Great! Thanks a lot @maurolepore

**Comment by MonikaFu** [comment]
@jdhoffa in commit 012c9e0 I added some code example of how one would set up the parameters and run the charts code, assuming that they have the right data. I hope that helps for now.

**Comment by maurolepore** [comment]
I highlight that https://github.com/2DegreesInvesting/r2dii.ggplot/issues/25 will remind us to transform the examples in README into examples in the helpfiles. As Jackson's suggestion won't fall through the cracks, in my opinion, you are good to go.

**Review by jdhoffa — APPROVED** [review]
sorry for the delay! I'm satisfied with this solution :-) 
lgtm

**Pull request merged**
